/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-3",
    "aws_cognito_identity_pool_id": "eu-west-3:094352be-af71-42b3-867c-0dcdaed91105",
    "aws_cognito_region": "eu-west-3",
    "aws_user_pools_id": "eu-west-3_cNyOylGaS",
    "aws_user_pools_web_client_id": "7ukr80tt6h1v0tju9c6ki7roe8",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "reactamplifiedb9c8b6db11b749539fb7102c3441c5b7161538-dev",
    "aws_user_files_s3_bucket_region": "eu-west-3"
};


export default awsmobile;
